# .github/workflows/daily-download.yml
name: Download the file from SBI server, at 3:00 PM everyday

on:
  schedule:
    # Runs "at 4:30 PM and 10:30 PM IST time (i.e. 10:30 AM and 4:30 PM UTC)" (see https://crontab.guru)
    - cron: "30 10,16 * * *"
  workflow_dispatch:


jobs:
  build:

    name: Download Rates FILE

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

      # libmagic is used to detect MIME type
    - name: Install libmagic
      run: |
        sudo apt-get update
        sudo apt-get install -y libmagic1

      # poppler is used to convert pdf to images
    - name: Install poppler
      run: |
        sudo apt-get install -y poppler-utils

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download and save file
      env:
        ANTHROPIC_API_KEY: ${{ secrets.anthropic_api_key }}
      run: python sbi_forex_downloader.py
      
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: "dddd, MMMM Do YYYY, h:mm:ss a"
        utcOffset: "+05:30"

      # Commit the PDF and the updated rates in csv
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto Commit: SBI rates at ${{ steps.current-time.outputs.formattedTime }}"name: SBI Forex Rates Downloader

on:
  schedule:
    # Runs at 11:00 AM IST (5:30 AM UTC)
    - cron: '30 5 * * *'
    # Runs at 1:00 PM IST (7:30 AM UTC)
    - cron: '30 7 * * *'
    # Runs at 5:00 PM IST (11:30 AM UTC)
    - cron: '30 11 * * *'
    # Runs at 6:00 PM IST (12:30 PM UTC)
    - cron: '30 12 * * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  download_forex_rates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyPDF2
    
    - name: Run downloader script
      run: python sbi_forex_downloader.py
    
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add downloads/
        git add data/
        git add *.log
        git diff --quiet && git diff --staged --quiet || git commit -m "Update forex rates $(date +'%Y-%m-%d %H:%M:%S')"
        git push
